"""Add notifications tables

Revision ID: 0eaa98a7c495
Revises: 32fe8d31c2fa
Create Date: 2025-05-07 20:13:55.451002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eaa98a7c495'
down_revision = '32fe8d31c2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('days_before', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hours_before', sa.Integer(), nullable=False))
        batch_op.drop_column('complaint_reply_enabled')
        batch_op.drop_column('deadline_days_before')
        batch_op.drop_column('deadline_enabled')
        batch_op.drop_column('deadline_hours_before')
        batch_op.drop_column('complaint_submitted_enabled')
        batch_op.drop_column('new_registration_enabled')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=19), nullable=False))

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_registration_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('complaint_submitted_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('deadline_hours_before', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('deadline_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('deadline_days_before', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('complaint_reply_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('hours_before')
        batch_op.drop_column('days_before')
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
