"""Initial migration

Revision ID: 22059d927f9d
Revises: b1ada50ef86b
Create Date: 2025-05-10 01:48:38.080100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22059d927f9d'
down_revision = 'b1ada50ef86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notification', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('admin_notification')

    # ### end Alembic commands ###
