"""Initial schema with only users & assignments

Revision ID: 32fe8d31c2fa
Revises: 2ce2c85a1a94
Create Date: 2025-05-07 17:24:09.129180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fe8d31c2fa'
down_revision = '2ce2c85a1a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deadline_enabled', sa.Boolean(), nullable=False),
    sa.Column('deadline_days_before', sa.Integer(), nullable=False),
    sa.Column('deadline_hours_before', sa.Integer(), nullable=False),
    sa.Column('complaint_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('new_registration_enabled', sa.Boolean(), nullable=False),
    sa.Column('complaint_submitted_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('deadline', 'complaint_reply', 'new_registration', 'complaint_submitted', name='notif_types'), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_timestamp'))

    op.drop_table('notifications')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
