"""Initial migration

Revision ID: 34ec9ccde258
Revises: 22059d927f9d
Create Date: 2025-05-10 15:30:05.215301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ec9ccde258'
down_revision = '22059d927f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.Enum('user', 'admin', name='notification_types'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
