"""Add enhanced notification settings

Revision ID: 358658291504
Revises: 707e070aa6a1
Create Date: 2025-05-10 21:12:57.685547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358658291504'
down_revision = '707e070aa6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topics', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_reminder_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_reminder_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_column('quiz_reminder_hours')
        batch_op.drop_column('quiz_reminder_days')

    op.drop_table('quiz')
    # ### end Alembic commands ###
