"""Add enhanced notification settings

Revision ID: 707e070aa6a1
Revises: dfd27b495ab0
Create Date: 2025-05-10 18:51:45.780685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707e070aa6a1'
down_revision = 'dfd27b495ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reminder_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_enabled', sa.Boolean(), nullable=True))
        batch_op.drop_column('admin_notifications_enabled')
        batch_op.drop_column('push_notifications')
        batch_op.drop_column('days_before')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('enabled')
        batch_op.drop_column('user_notifications_enabled')
        batch_op.drop_column('hours_before')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_before', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_notifications_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('days_before', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('push_notifications', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('admin_notifications_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('admin_enabled')
        batch_op.drop_column('reminder_hours')
        batch_op.drop_column('reminder_days')
        batch_op.drop_column('student_enabled')

    # ### end Alembic commands ###
