"""Add enhanced notification settings

Revision ID: af4dfbe83fc6
Revises: 358658291504
Create Date: 2025-05-10 21:33:21.444593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4dfbe83fc6'
down_revision = '358658291504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.alter_column('quiz_reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quiz_reminder_hours',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.alter_column('quiz_reminder_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quiz_reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
