"""Add enhanced notification settings

Revision ID: dfd27b495ab0
Revises: 34ec9ccde258
Create Date: 2025-05-10 17:39:25.371164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd27b495ab0'
down_revision = '34ec9ccde258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_notifications', sa.Boolean(), nullable=True))
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('days_before',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hours_before',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.alter_column('hours_before',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('days_before',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('push_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('user_notifications_enabled')
        batch_op.drop_column('admin_notifications_enabled')

    # ### end Alembic commands ###
