"""Add enhanced notification settings

Revision ID: e1dea5eb0fba
Revises: af4dfbe83fc6
Create Date: 2025-05-10 22:11:15.557228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1dea5eb0fba'
down_revision = 'af4dfbe83fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_notification_settings')
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.alter_column('quiz_reminder_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quiz_reminder_hours',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.alter_column('quiz_reminder_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quiz_reminder_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_notification_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('reminder_days', sa.INTEGER(), nullable=True),
    sa.Column('reminder_hours', sa.INTEGER(), nullable=True),
    sa.Column('admin_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_reminder_days', sa.INTEGER(), nullable=False),
    sa.Column('quiz_reminder_hours', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
